# Generated by Django 2.1 on 2018-08-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Post',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
