# Generated by Django 2.1 on 2018-08-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180807_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.CharField(default='static/images/default.jpg', max_length=500),
        ),
    ]
